# Generated by Django 6.1 on 2026-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('VE', 'Vegetable'), ('FR', 'Fruit'), ('GR', 'Grain'), ('DA', 'Dairy'), ('OT', 'Other')], default='OT', max_length=2)),
                ('kcal', models.IntegerField(default=0, max_length=5)),
                ('saturatedfat', models.IntegerField(default=0, max_length=5)),
                ('transfat', models.IntegerField(default=0, max_length=5)),
                ('cholesterol', models.IntegerField(default=0, max_length=5)),
                ('fiber', models.IntegerField(default=0, max_length=5)),
                ('sugar', models.IntegerField(default=0, max_length=5)),
                ('protein', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food', models.ManyToManyField(to='food_app.food')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('meal', models.ManyToManyField(to='food_app.meal')),
            ],
        ),
    ]
