# Generated by Django 6.1 on 2026-08-14 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food',
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturatedfat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='transfat',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_app.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', related_query_name='meal', to='food_app.day')),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_app.meal')),
            ],
        ),
    ]
