# Generated by Django 6.1 on 2026-08-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        ('food_app', '0002_remove_day_meal_remove_meal_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', related_query_name='day', to='client_app.client'),
            preserve_default=False,
        ),
    ]
