# Generated by Django 6.1 on 2026-08-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_day_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='type',
            new_name='food_type',
        ),
    ]
