# Generated by Django 5.0.3 on 2026-08-23 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_rename_type_food_food_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='client',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='created_foods', related_query_name='created_food', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
