# Generated by Django 5.0.3 on 2026-08-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_rename_client_day_owner_food_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='saturatedfat',
            new_name='saturated_fat',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='transfat',
            new_name='trans_fat',
        ),
    ]
