# Generated by Django 5.0.3 on 2026-08-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_rename_saturatedfat_food_saturated_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('VE', 'Vegetable'), ('FR', 'Fruit'), ('GR', 'Grain'), ('DA', 'Dairy'), ('PR', 'Protein'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
