# Generated by Django 5.0.3 on 2026-08-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_externalfood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalFood',
        ),
    ]
