# Generated by Django 5.0.3 on 2026-08-31 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0009_delete_externalfood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='day',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='days', related_query_name='day', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.food'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='MealItem',
        ),
    ]
