services:
  db:
    image: postgres:15
    container_name: cc-db-container
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  django:
    build: ./backend/calorie_crusher_proj/.
    container_name: cc-django-container
    command: sh -c "python manage.py migrate && gunicorn calorie_crusher_proj.wsgi --bind 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - ./db/.env
      - ./backend/.env
    volumes:
      - ./backend/calorie_crusher_proj/:/app
    depends_on:
      - db

  nginx:
    build: ./frontend/CalorieCrusher
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django