services:
  db:
    image: postgres:15
    container_name: cc-db-container
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  django:
    build: ./backend/.
    container_name: cc-django-container
    ports:
      - "8000:8000"
    env_file:
      - ./db/.env
      - ./backend/.env
    volumes:
      - ./db/calorie_crusher_proj:/app
    depends_on:
      - db