# Generated by Django 6.1 on 2026-08-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='defaultusername', max_length=30)),
                ('email', models.CharField(default='defaultusername', max_length=30)),
            ],
        ),
    ]
