# Generated by Django 5.0.3 on 2026-08-20 20:44

import client_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(default=None, max_length=30, unique=True, validators=[client_app.validators.username_format_validate]),
        ),
    ]
