# Generated by Django 5.0.3 on 2026-08-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_alter_client_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
