# Generated by Django 5.0.3 on 2026-08-24 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_alter_client_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(48), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='client',
            name='target_weight',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
