# Generated by Django 5.0.3 on 2026-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_client_height_client_target_weight_client_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fat_secret_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
