# Generated by Django 5.0.3 on 2026-08-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_client_fat_secret_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fat_secret_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
