# Generated by Django 5.0.3 on 2026-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_client_fat_secret_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fat_secret_token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
